#
POST http://localhost:3000/api/wilder HTTP/1.1
Content-Type: application/json

{
    "name": "hHyyt",
    "city": "ashas",
    "skills": [
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

###
GET http://localhost:3000/api/wilder HTTP/1.1


### Update
PUT http://localhost:3000/api/wilder
Content-Type: application/json

{
  "_id": "6141b2e55e8cb31435cb2968",
  "name" : "mooomooooooooooo"
}

### Delete
DELETE http://localhost:3000/api/wilder HTTP/1.1
Content-Type: application/json

{
  "_id": "6141fe17e7adfa0eab13e796"
}